"""Initial migration

Revision ID: 92df4d5f676a
Revises: 
Create Date: 2026-04-22 10:28:20.403442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92df4d5f676a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'rolemodulepermission', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'rolemodulepermission', 'modulepermission', ['module_permission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rolemodulepermission', type_='foreignkey')
    op.drop_constraint(None, 'rolemodulepermission', type_='foreignkey')
    # ### end Alembic commands ###
