"""Add BlacklistPerson table

Revision ID: a0fb05fb8d95
Revises: 92df4d5f676a
Create Date: 2026-05-06 12:42:23.293572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a0fb05fb8d95'
down_revision: Union[str, Sequence[str], None] = '92df4d5f676a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create BlacklistPerson table
    op.create_table('blacklistperson',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('image_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # commands auto generated by Alembic - please adjust!
    op.alter_column('camera', 'enabled_scenario_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('detectionevent', 'is_resolved',
               existing_type=sa.BOOLEAN(),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('blacklistperson')
    op.alter_column('detectionevent', 'is_resolved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('camera', 'enabled_scenario_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
